// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ROBOTApocalypse.DB;

#nullable disable

namespace ROBOTApocalypse.DB.Migrations
{
    [DbContext(typeof(ROBOTApocalypseDBContext))]
    [Migration("20220223105915_removedVirtualKeyword")]
    partial class removedVirtualKeyword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ROBOTApocalypse.Entity.SurvivorLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SurvivorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SurvivorId")
                        .IsUnique();

                    b.ToTable("SurvivorLocation");
                });

            modelBuilder.Entity("ROBOTApocalypse.Entity.Survivors", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Ammunition")
                        .HasColumnType("int");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Survivors");
                });

            modelBuilder.Entity("ROBOTApocalypse.Entity.SurvivorLocation", b =>
                {
                    b.HasOne("ROBOTApocalypse.Entity.Survivors", "Survivors")
                        .WithOne("SurvivorLocation")
                        .HasForeignKey("ROBOTApocalypse.Entity.SurvivorLocation", "SurvivorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survivors");
                });

            modelBuilder.Entity("ROBOTApocalypse.Entity.Survivors", b =>
                {
                    b.Navigation("SurvivorLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
